package frc.tecdroid3354.subsystems.Hood

import edu.wpi.first.units.measure.Angle
import edu.wpi.first.wpilibj.Alert
import edu.wpi.first.wpilibj2.command.SubsystemBase
import frc.tecdroid3354.constants.SubsystemsControlGains
import frc.tecdroid3354.constants.SubsystemsPresetTargets
import frc.tecdroid3354.constants.SubsystemsTunableTargets
import frc.tecdroid3354.utils.degrees
import frc.tecdroid3354.utils.interfaces.MotorIOInputsAutoLogged
import org.littletonrobotics.junction.Logger

class HoodSubsystem(private val io: HoodIO): SubsystemBase(HoodConstants.Telemetry.SUBSYSTEM_TAB) {
    // Auto generated by @AutoLog in IO layer
    private val inputs: HoodIOInputsAutoLogged = HoodIOInputsAutoLogged()
    private val leadMotorInputs: MotorIOInputsAutoLogged = MotorIOInputsAutoLogged()
    private val followerMotorInputs: MotorIOInputsAutoLogged = MotorIOInputsAutoLogged()

    private val leadMotorDisconnectedAlert: Alert =
        Alert(HoodConstants.Telemetry.LEAD_MOTOR_CONNECTION_ALERT_TAB, Alert.AlertType.kError)
    private val followerMotorDisconnectedAlert: Alert =
        Alert(HoodConstants.Telemetry.FOLLOWER_MOTOR_CONNECTION_ALERT_TAB, Alert.AlertType.kError)

    init {
        io.initialMotorConfiguration()
    }

    override fun periodic() {
        io.updateHoodInputs(inputs, leadMotorInputs, followerMotorInputs)
        Logger.processInputs(HoodConstants.Telemetry.SUBSYSTEM_TAB, inputs)
        Logger.processInputs(HoodConstants.Telemetry.LEAD_MOTOR_INPUTS_TAB, leadMotorInputs)
        Logger.processInputs(HoodConstants.Telemetry.FOLLOWER_MOTOR_INPUTS_TAB, followerMotorInputs)

        // Updates each alert based on the retrieved connectivity status of this cycle.
        // alert = notConnected ? true : false
        leadMotorDisconnectedAlert.set(leadMotorInputs.isConnected.not())
        followerMotorDisconnectedAlert.set(followerMotorInputs.isConnected.not())

        // Update 2d and 3d (if applicable) visualization of the mechanism. Mechanism is logged inside the method.
        //visualizer.updateElevatorVisualization(inputs.elevatorDisplacement)

        if (SubsystemsControlGains.HOOD_MOTOR_PRIMARY_GAINS.hadTunableUpdated()) {
            io.updateHoodMotorsControlGains(0) // Updates slot0 because is the primary set
        }

        if (SubsystemsTunableTargets.HOOD_MANUAL_TARGET_DEGREES.hasChanged(hashCode())) {
            io.updateHoodManualPosition(SubsystemsTunableTargets.HOOD_MANUAL_TARGET_DEGREES.get().degrees)
        }
    }

    fun setHoodManualPosition(): Runnable {
        return io.setHoodManualPosition()
    }

    fun setHoodPosition(hoodPosition: Angle): Runnable {
        return io.setHoodPosition(hoodPosition)
    }

    fun setHoodHomePosition(): Runnable {
        return io.setHoodPosition(SubsystemsPresetTargets.HOOD_HOME_ANGLE)
    }

    fun stopHood(): Runnable {
        return io.stopHood()
    }

    fun getHoodPosition(): Angle = inputs.hoodActualPosition

    fun coastHood(): Runnable {
        return io.coastHoodMotors()
    }

    fun brakeHood(): Runnable {
        return io.brakeHoodMotors()
    }
}