package frc.tecdroid3354.subsystems.Hood

import edu.wpi.first.units.measure.Angle
import edu.wpi.first.units.measure.Distance
import edu.wpi.first.wpilibj.Alert
import edu.wpi.first.wpilibj2.command.Command
import edu.wpi.first.wpilibj2.command.RunCommand
import edu.wpi.first.wpilibj2.command.SubsystemBase
import frc.tecdroid3354.constants.SubsystemsControlGains
import frc.tecdroid3354.constants.SubsystemsPresetTargets
import frc.tecdroid3354.constants.SubsystemsTunableTargets
import frc.tecdroid3354.utils.InstantCommand
import frc.tecdroid3354.utils.degrees
import frc.tecdroid3354.utils.interfaces.MotorIOInputsAutoLogged
import frc.tecdroid3354.utils.meters
import org.littletonrobotics.junction.Logger
import java.util.function.Supplier

class HoodSubsystem(private val io: HoodIO): SubsystemBase(HoodConstants.Telemetry.SUBSYSTEM_TAB) {
    // Auto generated by @AutoLog in IO layer
    private val inputs: HoodIOInputsAutoLogged = HoodIOInputsAutoLogged()
    private val leadMotorInputs: MotorIOInputsAutoLogged = MotorIOInputsAutoLogged()

    private val leadMotorDisconnectedAlert: Alert =
        Alert(HoodConstants.Telemetry.LEAD_MOTOR_CONNECTION_ALERT_TAB, Alert.AlertType.kError)

    init {
        io.initialMotorConfiguration()
    }

    override fun periodic() {
        io.updateHoodInputs(inputs, leadMotorInputs)
        Logger.processInputs(HoodConstants.Telemetry.SUBSYSTEM_TAB, inputs)
        Logger.processInputs(HoodConstants.Telemetry.LEAD_MOTOR_INPUTS_TAB, leadMotorInputs)

        // Updates each alert based on the retrieved connectivity status of this cycle.
        // alert = notConnected ? true : false
        leadMotorDisconnectedAlert.set(leadMotorInputs.isConnected.not())

        // Update 2d and 3d (if applicable) visualization of the mechanism. Mechanism is logged inside the method.
        //visualizer.updateElevatorVisualization(inputs.elevatorDisplacement)

        if (SubsystemsControlGains.HOOD_MOTOR_PRIMARY_GAINS.hadTunableUpdated()) {
            io.updateHoodMotorsControlGains(0) // Updates slot0 because is the primary set
        }

        if (SubsystemsTunableTargets.HOOD_MANUAL_TARGET_DEGREES.hasChanged(hashCode())) {
            io.updateHoodManualPosition(SubsystemsTunableTargets.HOOD_MANUAL_TARGET_DEGREES.get().degrees)
        }
    }

    fun setHoodManualPosition(): Runnable {
        return io.setHoodManualPosition()
    }

    fun setHoodPosition(hoodPosition: Angle): Runnable {
        return io.setHoodPosition(hoodPosition)
    }

    fun setHoodScoringPosition(flywheelDistanceToTarget: Supplier<Distance>): Command {
        // The .run() is because of how Runnables work, it ensures it runs again and doesn't freeze (even inside a RunCommand)
        return RunCommand({ io.setHoodPosition(getCalculatedHoodScoringAngle(flywheelDistanceToTarget.get())).run() }, this)
    }

    fun setHoodAssistPosition(flywheelDistanceToTarget: Supplier<Distance>): Command {
        // The .run() is because of how Runnables work, it ensures it runs again and doesn't freeze (even inside a RunCommand)
        return RunCommand({ io.setHoodPosition(getCalculatedHoodAssistAngle(flywheelDistanceToTarget.get())).run() }, this)
    }

    fun setHoodHomePosition(): Runnable {
        return io.setHoodPosition(SubsystemsPresetTargets.HOOD_HOME_ANGLE)
    }

    fun stopHood(): Runnable {
        return io.stopHood()
    }

    fun getHoodPosition(): Angle = inputs.hoodActualPosition

    fun coastHood(): Command {
        return io.coastHoodMotors().InstantCommand(this)
    }

    fun brakeHood(): Command {
        return io.brakeHoodMotors().InstantCommand(this)
    }

    /**
     * Uses the stored scoring polynomial in [HoodConstants.StoredPolynomials] and evaluates
     * with the given flywheel distance to target.
     *
     *
     * Assumed Units:
     *
     *   - Distance: Meters
     *
     *   - Polynomial Output: Degrees
     *
     * @param flywheelDistanceToTarget Differs from robot distance to target; account for offsets from robot center.
     * @return The [Angle] calculated by the scoring polynomial.
     */
    private fun getCalculatedHoodScoringAngle(flywheelDistanceToTarget: Distance): Angle {
        val distanceInMeters = flywheelDistanceToTarget.meters
        val calculatedAngle = HoodConstants.StoredPolynomials.SCORING_POLYNOMIAL.getOrThrow().evaluate(distanceInMeters)

        return calculatedAngle.degrees
    }

    /**
     * Uses the stored assist polynomial in [HoodConstants.StoredPolynomials] and evaluates
     * with the given flywheel distance to target.
     *
     *
     * Assumed Units:
     *
     *   - Distance: Meters
     *
     *   - Polynomial Output: Degrees
     *
     * @param flywheelDistanceToTarget Differs from robot distance to target; account for offsets from robot center.
     * @return The [Angle] calculated by the assist polynomial.
     */
    private fun getCalculatedHoodAssistAngle(flywheelDistanceToTarget: Distance): Angle {
        val distanceInMeters = flywheelDistanceToTarget.meters
        val calculatedAngle = HoodConstants.StoredPolynomials.ASSIST_POLYNOMIAL.getOrThrow().evaluate(distanceInMeters)

        return calculatedAngle.degrees
    }
}